SM-6890 - Update pagination docs
departmentfortransport/street-manager-docs pull request #784
Opened 2021-07-23 14:56 UTC by e-mccoy

2021-07-23 15:25 UTC, lukeca362 approved these changes

2021-07-28 11:08 UTC, cpaul92 requested changes

2021-07-28 11:08 UTC, cpaul92 commented on docs/_includes/api-documentation/v3/resource-guide.md
> +In any case, a maximum of 100 results will be returned.
```suggestion
In any case, a maximum of 100 results will be returned per request. If additional results exist the `next_update` property will be populated with the `update_id` of the next result allowing for further queries on the remaining results.
```

2021-07-28 14:49 UTC, lukeca362 commented on docs/_includes/api-documentation/v3/resource-guide.md
> +In any case, a maximum of 100 results will be returned.
This has now been added 👍🏻

2021-07-28 15:03 UTC, cpaul92 approved these changes

2021-07-29 09:29 UTC, merged